framework:
    messenger:
        transports:
            async_contact:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\PersonContactTask': async_contact